import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { getServerSession } from 'next-auth'
import SessionProvider from './components/SessionProvider'
import Auth from './components/Auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

export default async function RootLayout(props: Props) {
  const session = await getServerSession()

  return (
    <html lang='en'>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Auth />
          {props.children}
        </SessionProvider>
      </body>
    </html>
  )
}
